class Constants():
    # -------------------------------------------------------------基本数据------------------------------------------------------------
    # 股票列表
    stock_basic = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                   'symbol': {'type': 'str', 'vaule': '股票代码', 'is_primary_key': 'no'},
                   'name': {'type': 'str', 'vaule': '股票名称', 'is_primary_key': 'no'},
                   'area': {'type': 'str', 'vaule': '所在地域', 'is_primary_key': 'no'},
                   'industry': {'type': 'str', 'vaule': '所属行业', 'is_primary_key': 'no'},
                   'fullname': {'type': 'str', 'vaule': '股票全称', 'is_primary_key': 'no'},
                   'enname': {'type': 'str', 'vaule': '英文全称', 'is_primary_key': 'no'},
                   'market': {'type': 'str', 'vaule': '市场类型 （主板/中小板/创业板）', 'is_primary_key': 'no'},
                   'exchange': {'type': 'str', 'vaule': '交易所代码', 'is_primary_key': 'no'},
                   'curr_type': {'type': 'str', 'vaule': '交易货币', 'is_primary_key': 'no'},
                   'list_status': {'type': 'str', 'vaule': '上市状态： L上市 D退市 P暂停上市', 'is_primary_key': 'no'},
                   'list_date': {'type': 'str', 'vaule': '上市日期', 'is_primary_key': 'no'},
                   'delist_date': {'type': 'str', 'vaule': '退市日期', 'is_primary_key': 'no'},
                   'is_hs': {'type': 'str', 'vaule': '是否沪深港通标的，N否 H沪股通 S深股通', 'is_primary_key': 'no'}}

    # 交易日历
    trade_cal = {'exchange': {'type': 'str', 'vaule': '交易所 SSE上交所 SZSE深交所', 'is_primary_key': 'yes'},
                 'cal_date': {'type': 'str', 'vaule': '日历日期', 'is_primary_key': 'yes'},
                 'is_open': {'type': 'int', 'vaule': '是否交易 0休市 1交易', 'is_primary_key': 'no'},
                 'pretrade_date': {'type': 'str', 'vaule': '上一个交易日', 'is_primary_key': 'no'}}

    # 沪深股通成份股
    hs_const = {'ts_code':{'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'no'},
                'hs_type': {'type': 'str', 'vaule': '沪深港通类型SH沪SZ深', 'is_primary_key': 'yes'},
                'in_date': {'type': 'str', 'vaule': '纳入日期', 'is_primary_key': 'yes'},
                'out_date': {'type': 'str', 'vaule': '剔除日期', 'is_primary_key': 'yes'},
                'is_new': {'type': 'str', 'vaule': '是否最新 1是 0否', 'is_primary_key': 'yes'}}

    # 股票曾用名
    namechange = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                  'name': {'type': 'str', 'vaule': '证券名称', 'is_primary_key': 'no'},
                  'start_date': {'type': 'str', 'vaule': '开始日期', 'is_primary_key': 'no'},
                  'end_date': {'type': 'str', 'vaule': '结束日期', 'is_primary_key': 'no'},
                  'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'yes'},
                  'change_reason': {'type': 'str', 'vaule': '变更原因', 'is_primary_key': 'no'}}

    # 上市公司基本信息
    stock_company = {'ts_code': {'type': 'str', 'vaule': '股票代码', 'is_primary_key': 'yes'},
                     'exchange': {'type': 'str', 'vaule': '交易所代码 ，SSE上交所 SZSE深交所', 'is_primary_key': 'no'},
                     'chairman': {'type': 'str', 'vaule': '法人代表', 'is_primary_key': 'no'},
                     'manager': {'type': 'str', 'vaule': '总经理', 'is_primary_key': 'no'},
                     'secretary': {'type': 'str', 'vaule': '董秘', 'is_primary_key': 'no'},
                     'reg_capital': {'type': 'float', 'vaule': '注册资本', 'is_primary_key': 'no'},
                     'setup_date': {'type': 'str', 'vaule': '注册日期', 'is_primary_key': 'no'},
                     'province': {'type': 'str', 'vaule': '所在省份', 'is_primary_key': 'no'},
                     'city': {'type': 'str', 'vaule': '所在城市', 'is_primary_key': 'no'},
                     'introduction': {'type': 'str', 'vaule': '公司介绍', 'is_primary_key': 'no'},
                     'website': {'type': 'str', 'vaule': '公司主页', 'is_primary_key': 'no'},
                     'email': {'type': 'str', 'vaule': '电子邮件', 'is_primary_key': 'no'},
                     'office': {'type': 'str', 'vaule': '办公室', 'is_primary_key': 'no'},
                     'employees': {'type': 'int', 'vaule': '员工人数', 'is_primary_key': 'no'},
                     'main_business': {'type': 'str', 'vaule': '主要业务及产品', 'is_primary_key': 'no'},
                     'business_scope': {'type': 'str', 'vaule': '经营范围', 'is_primary_key': 'no'}}


    # ------------------------------------------------------------行情数据------------------------------------------------------------
    # 日线行情
    daily = {'ts_code': {'type': 'str', 'vaule': '股票代码', 'is_primary_key': 'yes'},
             'trade_date': {'type': 'str', 'vaule': '交易日期', 'is_primary_key': 'yes'},
             'open': {'type': 'float', 'vaule': '开盘价', 'is_primary_key': 'no'},
             'high': {'type': 'float', 'vaule': '最高价', 'is_primary_key': 'no'},
             'low': {'type': 'float', 'vaule': '最低价', 'is_primary_key': 'no'},
             'close': {'type': 'float', 'vaule': '收盘价', 'is_primary_key': 'no'},
             'pre_close': {'type': 'float', 'vaule': '昨收价', 'is_primary_key': 'no'},
             'change': {'type': 'float', 'vaule': '涨跌额', 'is_primary_key': 'no'},
             'pct_chg': {'type': 'float', 'vaule': '涨跌幅 （未复权)', 'is_primary_key': 'no'},
             'vol': {'type': 'float', 'vaule': '成交量 （手）', 'is_primary_key': 'no'},
             'amount': {'type': 'float', 'vaule': '成交额 （千元）', 'is_primary_key': 'no'},
             'turnover_rate': {'type': 'float', 'vaule': '换手率（%）', 'is_primary_key': 'no'},
             'turnover_rate_f': {'type': 'float', 'vaule': '换手率（自由流通股）', 'is_primary_key': 'no'},
             'volume_ratio': {'type': 'float', 'vaule': '量比', 'is_primary_key': 'no'},
             'pe': {'type': 'float', 'vaule': '市盈率（总市值/净利润）', 'is_primary_key': 'no'},
             'pe_ttm': {'type': 'float', 'vaule': '市盈率（TTM）', 'is_primary_key': 'no'},
             'pb': {'type': 'float', 'vaule': '市净率（总市值/净资产）', 'is_primary_key': 'no'},
             'ps': {'type': 'float', 'vaule': '市销率', 'is_primary_key': 'no'},
             'ps_ttm': {'type': 'float', 'vaule': '市销率（TTM）', 'is_primary_key': 'no'},
             'total_share': {'type': 'float', 'vaule': '总股本 （万股）', 'is_primary_key': 'no'},
             'float_share': {'type': 'float', 'vaule': '流通股本 （万股）', 'is_primary_key': 'no'},
             'free_share': {'type': 'float', 'vaule': '自由流通股本 （万）', 'is_primary_key': 'no'},
             'total_mv': {'type': 'float', 'vaule': '总市值 （万元）', 'is_primary_key': 'no'},
             'circ_mv': {'type': 'float', 'vaule': '流通市值（万元）', 'is_primary_key': 'no'},
             }

    # -------------------------------------------------------------财务数据------------------------------------------------------------
    # 利润表
    income = {'ts_code': {'type': 'str', 'vaule': 'TS股票代码', 'is_primary_key': 'yes'},
              'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
              'f_ann_date': {'type': 'str', 'vaule': '实际公告日期，即发生过数据变更的最终日期', 'is_primary_key': 'no'},
              'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
              'report_type': {'type': 'str', 'vaule': '报告类型： 参考下表说明', 'is_primary_key': 'no'},
              'comp_type': {'type': 'str', 'vaule': '公司类型：1一般工商业 2银行 3保险 4证券', 'is_primary_key': 'no'},
              'basic_eps': {'type': 'float', 'vaule': '基本每股收益', 'is_primary_key': 'no'},
              'diluted_eps': {'type': 'float', 'vaule': '稀释每股收益', 'is_primary_key': 'no'},
              'total_revenue': {'type': 'float', 'vaule': '营业总收入 (元，下同)', 'is_primary_key': 'no'},
              'revenue': {'type': 'float', 'vaule': '营业收入', 'is_primary_key': 'no'},
              'int_income': {'type': 'float', 'vaule': '利息收入', 'is_primary_key': 'no'},
              'prem_earned': {'type': 'float', 'vaule': '已赚保费', 'is_primary_key': 'no'},
              'comm_income': {'type': 'float', 'vaule': '手续费及佣金收入', 'is_primary_key': 'no'},
              'n_commis_income': {'type': 'float', 'vaule': '手续费及佣金净收入', 'is_primary_key': 'no'},
              'n_oth_income': {'type': 'float', 'vaule': '其他经营净收益', 'is_primary_key': 'no'},
              'n_oth_b_income': {'type': 'float', 'vaule': '加:其他业务净收益', 'is_primary_key': 'no'},
              'prem_income': {'type': 'float', 'vaule': '保险业务收入', 'is_primary_key': 'no'},
              'out_prem': {'type': 'float', 'vaule': '减:分出保费', 'is_primary_key': 'no'},
              'une_prem_reser': {'type': 'float', 'vaule': '提取未到期责任准备金', 'is_primary_key': 'no'},
              'reins_income': {'type': 'float', 'vaule': '其中:分保费收入', 'is_primary_key': 'no'},
              'n_sec_tb_income': {'type': 'float', 'vaule': '代理买卖证券业务净收入', 'is_primary_key': 'no'},
              'n_sec_uw_income': {'type': 'float', 'vaule': '证券承销业务净收入', 'is_primary_key': 'no'},
              'n_asset_mg_income': {'type': 'float', 'vaule': '受托客户资产管理业务净收入', 'is_primary_key': 'no'},
              'oth_b_income': {'type': 'float', 'vaule': '其他业务收入', 'is_primary_key': 'no'},
              'fv_value_chg_gain': {'type': 'float', 'vaule': '加:公允价值变动净收益', 'is_primary_key': 'no'},
              'invest_income': {'type': 'float', 'vaule': '加:投资净收益', 'is_primary_key': 'no'},
              'ass_invest_income': {'type': 'float', 'vaule': '其中:对联营企业和合营企业的投资收益', 'is_primary_key': 'no'},
              'forex_gain': {'type': 'float', 'vaule': '加:汇兑净收益', 'is_primary_key': 'no'},
              'total_cogs': {'type': 'float', 'vaule': '营业总成本', 'is_primary_key': 'no'},
              'oper_cost': {'type': 'float', 'vaule': '减:营业成本', 'is_primary_key': 'no'},
              'int_exp': {'type': 'float', 'vaule': '减:利息支出', 'is_primary_key': 'no'},
              'comm_exp': {'type': 'float', 'vaule': '减:手续费及佣金支出', 'is_primary_key': 'no'},
              'biz_tax_surchg': {'type': 'float', 'vaule': '减:营业税金及附加', 'is_primary_key': 'no'},
              'sell_exp': {'type': 'float', 'vaule': '减:销售费用', 'is_primary_key': 'no'},
              'admin_exp': {'type': 'float', 'vaule': '减:管理费用', 'is_primary_key': 'no'},
              'fin_exp': {'type': 'float', 'vaule': '减:财务费用', 'is_primary_key': 'no'},
              'assets_impair_loss': {'type': 'float', 'vaule': '减:资产减值损失', 'is_primary_key': 'no'},
              'prem_refund': {'type': 'float', 'vaule': '退保金', 'is_primary_key': 'no'},
              'compens_payout': {'type': 'float', 'vaule': '赔付总支出', 'is_primary_key': 'no'},
              'reser_insur_liab': {'type': 'float', 'vaule': '提取保险责任准备金', 'is_primary_key': 'no'},
              'div_payt': {'type': 'float', 'vaule': '保户红利支出', 'is_primary_key': 'no'},
              'reins_exp': {'type': 'float', 'vaule': '分保费用', 'is_primary_key': 'no'},
              'oper_exp': {'type': 'float', 'vaule': '营业支出', 'is_primary_key': 'no'},
              'compens_payout_refu': {'type': 'float', 'vaule': '减:摊回赔付支出', 'is_primary_key': 'no'},
              'insur_reser_refu': {'type': 'float', 'vaule': '减:摊回保险责任准备金', 'is_primary_key': 'no'},
              'reins_cost_refund': {'type': 'float', 'vaule': '减:摊回分保费用', 'is_primary_key': 'no'},
              'other_bus_cost': {'type': 'float', 'vaule': '其他业务成本', 'is_primary_key': 'no'},
              'operate_profit': {'type': 'float', 'vaule': '营业利润', 'is_primary_key': 'no'},
              'non_oper_income': {'type': 'float', 'vaule': '加:营业外收入', 'is_primary_key': 'no'},
              'non_oper_exp': {'type': 'float', 'vaule': '减:营业外支出', 'is_primary_key': 'no'},
              'nca_disploss': {'type': 'float', 'vaule': '其中:减:非流动资产处置净损失', 'is_primary_key': 'no'},
              'total_profit': {'type': 'float', 'vaule': '利润总额', 'is_primary_key': 'no'},
              'income_tax': {'type': 'float', 'vaule': '所得税费用', 'is_primary_key': 'no'},
              'n_income': {'type': 'float', 'vaule': '净利润(含少数股东损益)', 'is_primary_key': 'no'},
              'n_income_attr_p': {'type': 'float', 'vaule': '净利润(不含少数股东损益)', 'is_primary_key': 'no'},
              'minority_gain': {'type': 'float', 'vaule': '少数股东损益', 'is_primary_key': 'no'},
              'oth_compr_income': {'type': 'float', 'vaule': '其他综合收益', 'is_primary_key': 'no'},
              't_compr_income': {'type': 'float', 'vaule': '综合收益总额', 'is_primary_key': 'no'},
              'compr_inc_attr_p': {'type': 'float', 'vaule': '归属于母公司(或股东)的综合收益总额', 'is_primary_key': 'no'},
              'compr_inc_attr_m_s': {'type': 'float', 'vaule': '归属于少数股东的综合收益总额', 'is_primary_key': 'no'},
              'ebit': {'type': 'float', 'vaule': '息税前利润', 'is_primary_key': 'no'},
              'ebitda': {'type': 'float', 'vaule': '息税折旧摊销前利润', 'is_primary_key': 'no'},
              'insurance_exp': {'type': 'float', 'vaule': '保险业务支出', 'is_primary_key': 'no'},
              'undist_profit': {'type': 'float', 'vaule': '年初未分配利润', 'is_primary_key': 'no'},
              'distable_profit': {'type': 'float', 'vaule': '可分配利润', 'is_primary_key': 'no'}}

    # 资产负债表
    balancesheet = {'ts_code': {'type': 'str', 'vaule': 'TS股票代码', 'is_primary_key': 'yes'},
                    'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
                    'f_ann_date': {'type': 'str', 'vaule': '实际公告日期', 'is_primary_key': 'no'},
                    'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
                    'report_type': {'type': 'str', 'vaule': '报表类型：见下方详细说明', 'is_primary_key': 'no'},
                    'comp_type': {'type': 'str', 'vaule': '公司类型：1一般工商业 2银行 3保险 4证券', 'is_primary_key': 'no'},
                    'total_share': {'type': 'float', 'vaule': '期末总股本', 'is_primary_key': 'no'},
                    'cap_rese': {'type': 'float', 'vaule': '资本公积金 (元，下同)', 'is_primary_key': 'no'},
                    'undistr_porfit': {'type': 'float', 'vaule': '未分配利润', 'is_primary_key': 'no'},
                    'surplus_rese': {'type': 'float', 'vaule': '盈余公积金', 'is_primary_key': 'no'},
                    'special_rese': {'type': 'float', 'vaule': '专项储备', 'is_primary_key': 'no'},
                    'money_cap': {'type': 'float', 'vaule': '货币资金', 'is_primary_key': 'no'},
                    'trad_asset': {'type': 'float', 'vaule': '交易性金融资产', 'is_primary_key': 'no'},
                    'notes_receiv': {'type': 'float', 'vaule': '应收票据', 'is_primary_key': 'no'},
                    'accounts_receiv': {'type': 'float', 'vaule': '应收账款', 'is_primary_key': 'no'},
                    'oth_receiv': {'type': 'float', 'vaule': '其他应收款', 'is_primary_key': 'no'},
                    'prepayment': {'type': 'float', 'vaule': '预付款项', 'is_primary_key': 'no'},
                    'div_receiv': {'type': 'float', 'vaule': '应收股利', 'is_primary_key': 'no'},
                    'int_receiv': {'type': 'float', 'vaule': '应收利息', 'is_primary_key': 'no'},
                    'inventories': {'type': 'float', 'vaule': '存货', 'is_primary_key': 'no'},
                    'amor_exp': {'type': 'float', 'vaule': '长期待摊费用', 'is_primary_key': 'no'},
                    'nca_within_1y': {'type': 'float', 'vaule': '一年内到期的非流动资产', 'is_primary_key': 'no'},
                    'sett_rsrv': {'type': 'float', 'vaule': '结算备付金', 'is_primary_key': 'no'},
                    'loanto_oth_bank_fi': {'type': 'float', 'vaule': '拆出资金', 'is_primary_key': 'no'},
                    'premium_receiv': {'type': 'float', 'vaule': '应收保费', 'is_primary_key': 'no'},
                    'reinsur_receiv': {'type': 'float', 'vaule': '应收分保账款', 'is_primary_key': 'no'},
                    'reinsur_res_receiv': {'type': 'float', 'vaule': '应收分保合同准备金', 'is_primary_key': 'no'},
                    'pur_resale_fa': {'type': 'float', 'vaule': '买入返售金融资产', 'is_primary_key': 'no'},
                    'oth_cur_assets': {'type': 'float', 'vaule': '其他流动资产', 'is_primary_key': 'no'},
                    'total_cur_assets': {'type': 'float', 'vaule': '流动资产合计', 'is_primary_key': 'no'},
                    'fa_avail_for_sale': {'type': 'float', 'vaule': '可供出售金融资产', 'is_primary_key': 'no'},
                    'htm_invest': {'type': 'float', 'vaule': '持有至到期投资', 'is_primary_key': 'no'},
                    'lt_eqt_invest': {'type': 'float', 'vaule': '长期股权投资', 'is_primary_key': 'no'},
                    'invest_real_estate': {'type': 'float', 'vaule': '投资性房地产', 'is_primary_key': 'no'},
                    'time_deposits': {'type': 'float', 'vaule': '定期存款', 'is_primary_key': 'no'},
                    'oth_assets': {'type': 'float', 'vaule': '其他资产', 'is_primary_key': 'no'},
                    'lt_rec': {'type': 'float', 'vaule': '长期应收款', 'is_primary_key': 'no'},
                    'fix_assets': {'type': 'float', 'vaule': '固定资产', 'is_primary_key': 'no'},
                    'cip': {'type': 'float', 'vaule': '在建工程', 'is_primary_key': 'no'},
                    'const_materials': {'type': 'float', 'vaule': '工程物资', 'is_primary_key': 'no'},
                    'fixed_assets_disp': {'type': 'float', 'vaule': '固定资产清理', 'is_primary_key': 'no'},
                    'produc_bio_assets': {'type': 'float', 'vaule': '生产性生物资产', 'is_primary_key': 'no'},
                    'oil_and_gas_assets': {'type': 'float', 'vaule': '油气资产', 'is_primary_key': 'no'},
                    'intan_assets': {'type': 'float', 'vaule': '无形资产', 'is_primary_key': 'no'},
                    'r_and_d': {'type': 'float', 'vaule': '研发支出', 'is_primary_key': 'no'},
                    'goodwill': {'type': 'float', 'vaule': '商誉', 'is_primary_key': 'no'},
                    'lt_amor_exp': {'type': 'float', 'vaule': '长期待摊费用', 'is_primary_key': 'no'},
                    'defer_tax_assets': {'type': 'float', 'vaule': '递延所得税资产', 'is_primary_key': 'no'},
                    'decr_in_disbur': {'type': 'float', 'vaule': '发放贷款及垫款', 'is_primary_key': 'no'},
                    'oth_nca': {'type': 'float', 'vaule': '其他非流动资产', 'is_primary_key': 'no'},
                    'total_nca': {'type': 'float', 'vaule': '非流动资产合计', 'is_primary_key': 'no'},
                    'cash_reser_cb': {'type': 'float', 'vaule': '现金及存放中央银行款项', 'is_primary_key': 'no'},
                    'depos_in_oth_bfi': {'type': 'float', 'vaule': '存放同业和其它金融机构款项', 'is_primary_key': 'no'},
                    'prec_metals': {'type': 'float', 'vaule': '贵金属', 'is_primary_key': 'no'},
                    'deriv_assets': {'type': 'float', 'vaule': '衍生金融资产', 'is_primary_key': 'no'},
                    'rr_reins_une_prem': {'type': 'float', 'vaule': '应收分保未到期责任准备金', 'is_primary_key': 'no'},
                    'rr_reins_outstd_cla': {'type': 'float', 'vaule': '应收分保未决赔款准备金', 'is_primary_key': 'no'},
                    'rr_reins_lins_liab': {'type': 'float', 'vaule': '应收分保寿险责任准备金', 'is_primary_key': 'no'},
                    'rr_reins_lthins_liab': {'type': 'float', 'vaule': '应收分保长期健康险责任准备金', 'is_primary_key': 'no'},
                    'refund_depos': {'type': 'float', 'vaule': '存出保证金', 'is_primary_key': 'no'},
                    'ph_pledge_loans': {'type': 'float', 'vaule': '保户质押贷款', 'is_primary_key': 'no'},
                    'refund_cap_depos': {'type': 'float', 'vaule': '存出资本保证金', 'is_primary_key': 'no'},
                    'indep_acct_assets': {'type': 'float', 'vaule': '独立账户资产', 'is_primary_key': 'no'},
                    'client_depos': {'type': 'float', 'vaule': '其中：客户资金存款', 'is_primary_key': 'no'},
                    'client_prov': {'type': 'float', 'vaule': '其中：客户备付金', 'is_primary_key': 'no'},
                    'transac_seat_fee': {'type': 'float', 'vaule': '其中:交易席位费', 'is_primary_key': 'no'},
                    'invest_as_receiv': {'type': 'float', 'vaule': '应收款项类投资', 'is_primary_key': 'no'},
                    'total_assets': {'type': 'float', 'vaule': '资产总计', 'is_primary_key': 'no'},
                    'lt_borr': {'type': 'float', 'vaule': '长期借款', 'is_primary_key': 'no'},
                    'st_borr': {'type': 'float', 'vaule': '短期借款', 'is_primary_key': 'no'},
                    'cb_borr': {'type': 'float', 'vaule': '向中央银行借款', 'is_primary_key': 'no'},
                    'depos_ib_deposits': {'type': 'float', 'vaule': '吸收存款及同业存放', 'is_primary_key': 'no'},
                    'loan_oth_bank': {'type': 'float', 'vaule': '拆入资金', 'is_primary_key': 'no'},
                    'trading_fl': {'type': 'float', 'vaule': '交易性金融负债', 'is_primary_key': 'no'},
                    'notes_payable': {'type': 'float', 'vaule': '应付票据', 'is_primary_key': 'no'},
                    'acct_payable': {'type': 'float', 'vaule': '应付账款', 'is_primary_key': 'no'},
                    'adv_receipts': {'type': 'float', 'vaule': '预收款项', 'is_primary_key': 'no'},
                    'sold_for_repur_fa': {'type': 'float', 'vaule': '卖出回购金融资产款', 'is_primary_key': 'no'},
                    'comm_payable': {'type': 'float', 'vaule': '应付手续费及佣金', 'is_primary_key': 'no'},
                    'payroll_payable': {'type': 'float', 'vaule': '应付职工薪酬', 'is_primary_key': 'no'},
                    'taxes_payable': {'type': 'float', 'vaule': '应交税费', 'is_primary_key': 'no'},
                    'int_payable': {'type': 'float', 'vaule': '应付利息', 'is_primary_key': 'no'},
                    'div_payable': {'type': 'float', 'vaule': '应付股利', 'is_primary_key': 'no'},
                    'oth_payable': {'type': 'float', 'vaule': '其他应付款', 'is_primary_key': 'no'},
                    'acc_exp': {'type': 'float', 'vaule': '预提费用', 'is_primary_key': 'no'},
                    'deferred_inc': {'type': 'float', 'vaule': '递延收益', 'is_primary_key': 'no'},
                    'st_bonds_payable': {'type': 'float', 'vaule': '应付短期债券', 'is_primary_key': 'no'},
                    'payable_to_reinsurer': {'type': 'float', 'vaule': '应付分保账款', 'is_primary_key': 'no'},
                    'rsrv_insur_cont': {'type': 'float', 'vaule': '保险合同准备金', 'is_primary_key': 'no'},
                    'acting_trading_sec': {'type': 'float', 'vaule': '代理买卖证券款', 'is_primary_key': 'no'},
                    'acting_uw_sec': {'type': 'float', 'vaule': '代理承销证券款', 'is_primary_key': 'no'},
                    'non_cur_liab_due_1y': {'type': 'float', 'vaule': '一年内到期的非流动负债', 'is_primary_key': 'no'},
                    'oth_cur_liab': {'type': 'float', 'vaule': '其他流动负债', 'is_primary_key': 'no'},
                    'total_cur_liab': {'type': 'float', 'vaule': '流动负债合计', 'is_primary_key': 'no'},
                    'bond_payable': {'type': 'float', 'vaule': '应付债券', 'is_primary_key': 'no'},
                    'lt_payable': {'type': 'float', 'vaule': '长期应付款', 'is_primary_key': 'no'},
                    'specific_payables': {'type': 'float', 'vaule': '专项应付款', 'is_primary_key': 'no'},
                    'estimated_liab': {'type': 'float', 'vaule': '预计负债', 'is_primary_key': 'no'},
                    'defer_tax_liab': {'type': 'float', 'vaule': '递延所得税负债', 'is_primary_key': 'no'},
                    'defer_inc_non_cur_liab': {'type': 'float', 'vaule': '递延收益-非流动负债', 'is_primary_key': 'no'},
                    'oth_ncl': {'type': 'float', 'vaule': '其他非流动负债', 'is_primary_key': 'no'},
                    'total_ncl': {'type': 'float', 'vaule': '非流动负债合计', 'is_primary_key': 'no'},
                    'depos_oth_bfi': {'type': 'float', 'vaule': '同业和其它金融机构存放款项', 'is_primary_key': 'no'},
                    'deriv_liab': {'type': 'float', 'vaule': '衍生金融负债', 'is_primary_key': 'no'},
                    'depos': {'type': 'float', 'vaule': '吸收存款', 'is_primary_key': 'no'},
                    'agency_bus_liab': {'type': 'float', 'vaule': '代理业务负债', 'is_primary_key': 'no'},
                    'oth_liab': {'type': 'float', 'vaule': '其他负债', 'is_primary_key': 'no'},
                    'prem_receiv_adva': {'type': 'float', 'vaule': '预收保费', 'is_primary_key': 'no'},
                    'depos_received': {'type': 'float', 'vaule': '存入保证金', 'is_primary_key': 'no'},
                    'ph_invest': {'type': 'float', 'vaule': '保户储金及投资款', 'is_primary_key': 'no'},
                    'reser_une_prem': {'type': 'float', 'vaule': '未到期责任准备金', 'is_primary_key': 'no'},
                    'reser_outstd_claims': {'type': 'float', 'vaule': '未决赔款准备金', 'is_primary_key': 'no'},
                    'reser_lins_liab': {'type': 'float', 'vaule': '寿险责任准备金', 'is_primary_key': 'no'},
                    'reser_lthins_liab': {'type': 'float', 'vaule': '长期健康险责任准备金', 'is_primary_key': 'no'},
                    'indept_acc_liab': {'type': 'float', 'vaule': '独立账户负债', 'is_primary_key': 'no'},
                    'pledge_borr': {'type': 'float', 'vaule': '其中:质押借款', 'is_primary_key': 'no'},
                    'indem_payable': {'type': 'float', 'vaule': '应付赔付款', 'is_primary_key': 'no'},
                    'policy_div_payable': {'type': 'float', 'vaule': '应付保单红利', 'is_primary_key': 'no'},
                    'total_liab': {'type': 'float', 'vaule': '负债合计', 'is_primary_key': 'no'},
                    'treasury_share': {'type': 'float', 'vaule': '减:库存股', 'is_primary_key': 'no'},
                    'ordin_risk_reser': {'type': 'float', 'vaule': '一般风险准备', 'is_primary_key': 'no'},
                    'forex_differ': {'type': 'float', 'vaule': '外币报表折算差额', 'is_primary_key': 'no'},
                    'invest_loss_unconf': {'type': 'float', 'vaule': '未确认的投资损失', 'is_primary_key': 'no'},
                    'minority_int': {'type': 'float', 'vaule': '少数股东权益', 'is_primary_key': 'no'},
                    'total_hldr_eqy_exc_min_int': {'type': 'float', 'vaule': '股东权益合计(不含少数股东权益)',
                                                   'is_primary_key': 'no'},
                    'total_hldr_eqy_inc_min_int': {'type': 'float', 'vaule': '股东权益合计(含少数股东权益)', 'is_primary_key': 'no'},
                    'total_liab_hldr_eqy': {'type': 'float', 'vaule': '负债及股东权益总计', 'is_primary_key': 'no'},
                    'lt_payroll_payable': {'type': 'float', 'vaule': '长期应付职工薪酬', 'is_primary_key': 'no'},
                    'oth_comp_income': {'type': 'float', 'vaule': '其他综合收益', 'is_primary_key': 'no'},
                    'oth_eqt_tools': {'type': 'float', 'vaule': '其他权益工具', 'is_primary_key': 'no'},
                    'oth_eqt_tools_p_shr': {'type': 'float', 'vaule': '其他权益工具(优先股)', 'is_primary_key': 'no'},
                    'lending_funds': {'type': 'float', 'vaule': '融出资金', 'is_primary_key': 'no'},
                    'acc_receivable': {'type': 'float', 'vaule': '应收款项', 'is_primary_key': 'no'},
                    'st_fin_payable': {'type': 'float', 'vaule': '应付短期融资款', 'is_primary_key': 'no'},
                    'payables': {'type': 'float', 'vaule': '应付款项', 'is_primary_key': 'no'},
                    'hfs_assets': {'type': 'float', 'vaule': '持有待售的资产', 'is_primary_key': 'no'},
                    'hfs_sales': {'type': 'float', 'vaule': '持有待售的负债', 'is_primary_key': 'no'}}

    # 现金流量表
    cashflow = {'ts_code': {'type': 'str', 'vaule': 'TS股票代码', 'is_primary_key': 'yes'},
                'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
                'f_ann_date': {'type': 'str', 'vaule': '实际公告日期', 'is_primary_key': 'no'},
                'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
                'comp_type': {'type': 'str', 'vaule': '公司类型：1一般工商业 2银行 3保险 4证券', 'is_primary_key': 'no'},
                'report_type': {'type': 'str', 'vaule': '报表类型：见下方详细说明', 'is_primary_key': 'no'},
                'net_profit': {'type': 'float', 'vaule': '净利润 (元，下同)', 'is_primary_key': 'no'},
                'finan_exp': {'type': 'float', 'vaule': '财务费用', 'is_primary_key': 'no'},
                'c_fr_sale_sg': {'type': 'float', 'vaule': '销售商品、提供劳务收到的现金', 'is_primary_key': 'no'},
                'recp_tax_rends': {'type': 'float', 'vaule': '收到的税费返还', 'is_primary_key': 'no'},
                'n_depos_incr_fi': {'type': 'float', 'vaule': '客户存款和同业存放款项净增加额', 'is_primary_key': 'no'},
                'n_incr_loans_cb': {'type': 'float', 'vaule': '向中央银行借款净增加额', 'is_primary_key': 'no'},
                'n_inc_borr_oth_fi': {'type': 'float', 'vaule': '向其他金融机构拆入资金净增加额', 'is_primary_key': 'no'},
                'prem_fr_orig_contr': {'type': 'float', 'vaule': '收到原保险合同保费取得的现金', 'is_primary_key': 'no'},
                'n_incr_insured_dep': {'type': 'float', 'vaule': '保户储金净增加额', 'is_primary_key': 'no'},
                'n_reinsur_prem': {'type': 'float', 'vaule': '收到再保业务现金净额', 'is_primary_key': 'no'},
                'n_incr_disp_tfa': {'type': 'float', 'vaule': '处置交易性金融资产净增加额', 'is_primary_key': 'no'},
                'ifc_cash_incr': {'type': 'float', 'vaule': '收取利息和手续费净增加额', 'is_primary_key': 'no'},
                'n_incr_disp_faas': {'type': 'float', 'vaule': '处置可供出售金融资产净增加额', 'is_primary_key': 'no'},
                'n_incr_loans_oth_bank': {'type': 'float', 'vaule': '拆入资金净增加额', 'is_primary_key': 'no'},
                'n_cap_incr_repur': {'type': 'float', 'vaule': '回购业务资金净增加额', 'is_primary_key': 'no'},
                'c_fr_oth_operate_a': {'type': 'float', 'vaule': '收到其他与经营活动有关的现金', 'is_primary_key': 'no'},
                'c_inf_fr_operate_a': {'type': 'float', 'vaule': '经营活动现金流入小计', 'is_primary_key': 'no'},
                'c_paid_goods_s': {'type': 'float', 'vaule': '购买商品、接受劳务支付的现金', 'is_primary_key': 'no'},
                'c_paid_to_for_empl': {'type': 'float', 'vaule': '支付给职工以及为职工支付的现金', 'is_primary_key': 'no'},
                'c_paid_for_taxes': {'type': 'float', 'vaule': '支付的各项税费', 'is_primary_key': 'no'},
                'n_incr_clt_loan_adv': {'type': 'float', 'vaule': '客户贷款及垫款净增加额', 'is_primary_key': 'no'},
                'n_incr_dep_cbob': {'type': 'float', 'vaule': '存放央行和同业款项净增加额', 'is_primary_key': 'no'},
                'c_pay_claims_orig_inco': {'type': 'float', 'vaule': '支付原保险合同赔付款项的现金', 'is_primary_key': 'no'},
                'pay_handling_chrg': {'type': 'float', 'vaule': '支付手续费的现金', 'is_primary_key': 'no'},
                'pay_comm_insur_plcy': {'type': 'float', 'vaule': '支付保单红利的现金', 'is_primary_key': 'no'},
                'oth_cash_pay_oper_act': {'type': 'float', 'vaule': '支付其他与经营活动有关的现金', 'is_primary_key': 'no'},
                'st_cash_out_act': {'type': 'float', 'vaule': '经营活动现金流出小计', 'is_primary_key': 'no'},
                'n_cashflow_act': {'type': 'float', 'vaule': '经营活动产生的现金流量净额', 'is_primary_key': 'no'},
                'oth_recp_ral_inv_act': {'type': 'float', 'vaule': '收到其他与投资活动有关的现金', 'is_primary_key': 'no'},
                'c_disp_withdrwl_invest': {'type': 'float', 'vaule': '收回投资收到的现金', 'is_primary_key': 'no'},
                'c_recp_return_invest': {'type': 'float', 'vaule': '取得投资收益收到的现金', 'is_primary_key': 'no'},
                'n_recp_disp_fiolta': {'type': 'float', 'vaule': '处置固定资产、无形资产和其他长期资产收回的现金净额', 'is_primary_key': 'no'},
                'n_recp_disp_sobu': {'type': 'float', 'vaule': '处置子公司及其他营业单位收到的现金净额', 'is_primary_key': 'no'},
                'stot_inflows_inv_act': {'type': 'float', 'vaule': '投资活动现金流入小计', 'is_primary_key': 'no'},
                'c_pay_acq_const_fiolta': {'type': 'float', 'vaule': '购建固定资产、无形资产和其他长期资产支付的现金', 'is_primary_key': 'no'},
                'c_paid_invest': {'type': 'float', 'vaule': '投资支付的现金', 'is_primary_key': 'no'},
                'n_disp_subs_oth_biz': {'type': 'float', 'vaule': '取得子公司及其他营业单位支付的现金净额', 'is_primary_key': 'no'},
                'oth_pay_ral_inv_act': {'type': 'float', 'vaule': '支付其他与投资活动有关的现金', 'is_primary_key': 'no'},
                'n_incr_pledge_loan': {'type': 'float', 'vaule': '质押贷款净增加额', 'is_primary_key': 'no'},
                'stot_out_inv_act': {'type': 'float', 'vaule': '投资活动现金流出小计', 'is_primary_key': 'no'},
                'n_cashflow_inv_act': {'type': 'float', 'vaule': '投资活动产生的现金流量净额', 'is_primary_key': 'no'},
                'c_recp_borrow': {'type': 'float', 'vaule': '取得借款收到的现金', 'is_primary_key': 'no'},
                'proc_issue_bonds': {'type': 'float', 'vaule': '发行债券收到的现金', 'is_primary_key': 'no'},
                'oth_cash_recp_ral_fnc_act': {'type': 'float', 'vaule': '收到其他与筹资活动有关的现金', 'is_primary_key': 'no'},
                'stot_cash_in_fnc_act': {'type': 'float', 'vaule': '筹资活动现金流入小计', 'is_primary_key': 'no'},
                'free_cashflow': {'type': 'float', 'vaule': '企业自由现金流量', 'is_primary_key': 'no'},
                'c_prepay_amt_borr': {'type': 'float', 'vaule': '偿还债务支付的现金', 'is_primary_key': 'no'},
                'c_pay_dist_dpcp_int_exp': {'type': 'float', 'vaule': '分配股利、利润或偿付利息支付的现金', 'is_primary_key': 'no'},
                'incl_dvd_profit_paid_sc_ms': {'type': 'float', 'vaule': '其中:子公司支付给少数股东的股利、利润', 'is_primary_key': 'no'},
                'oth_cashpay_ral_fnc_act': {'type': 'float', 'vaule': '支付其他与筹资活动有关的现金', 'is_primary_key': 'no'},
                'stot_cashout_fnc_act': {'type': 'float', 'vaule': '筹资活动现金流出小计', 'is_primary_key': 'no'},
                'n_cash_flows_fnc_act': {'type': 'float', 'vaule': '筹资活动产生的现金流量净额', 'is_primary_key': 'no'},
                'eff_fx_flu_cash': {'type': 'float', 'vaule': '汇率变动对现金的影响', 'is_primary_key': 'no'},
                'n_incr_cash_cash_equ': {'type': 'float', 'vaule': '现金及现金等价物净增加额', 'is_primary_key': 'no'},
                'c_cash_equ_beg_period': {'type': 'float', 'vaule': '期初现金及现金等价物余额', 'is_primary_key': 'no'},
                'c_cash_equ_end_period': {'type': 'float', 'vaule': '期末现金及现金等价物余额', 'is_primary_key': 'no'},
                'c_recp_cap_contrib': {'type': 'float', 'vaule': '吸收投资收到的现金', 'is_primary_key': 'no'},
                'incl_cash_rec_saims': {'type': 'float', 'vaule': '其中:子公司吸收少数股东投资收到的现金', 'is_primary_key': 'no'},
                'uncon_invest_loss': {'type': 'float', 'vaule': '未确认投资损失', 'is_primary_key': 'no'},
                'prov_depr_assets': {'type': 'float', 'vaule': '加:资产减值准备', 'is_primary_key': 'no'},
                'depr_fa_coga_dpba': {'type': 'float', 'vaule': '固定资产折旧、油气资产折耗、生产性生物资产折旧', 'is_primary_key': 'no'},
                'amort_intang_assets': {'type': 'float', 'vaule': '无形资产摊销', 'is_primary_key': 'no'},
                'lt_amort_deferred_exp': {'type': 'float', 'vaule': '长期待摊费用摊销', 'is_primary_key': 'no'},
                'decr_deferred_exp': {'type': 'float', 'vaule': '待摊费用减少', 'is_primary_key': 'no'},
                'incr_acc_exp': {'type': 'float', 'vaule': '预提费用增加', 'is_primary_key': 'no'},
                'loss_disp_fiolta': {'type': 'float', 'vaule': '处置固定、无形资产和其他长期资产的损失', 'is_primary_key': 'no'},
                'loss_scr_fa': {'type': 'float', 'vaule': '固定资产报废损失', 'is_primary_key': 'no'},
                'loss_fv_chg': {'type': 'float', 'vaule': '公允价值变动损失', 'is_primary_key': 'no'},
                'invest_loss': {'type': 'float', 'vaule': '投资损失', 'is_primary_key': 'no'},
                'decr_def_inc_tax_assets': {'type': 'float', 'vaule': '递延所得税资产减少', 'is_primary_key': 'no'},
                'incr_def_inc_tax_liab': {'type': 'float', 'vaule': '递延所得税负债增加', 'is_primary_key': 'no'},
                'decr_inventories': {'type': 'float', 'vaule': '存货的减少', 'is_primary_key': 'no'},
                'decr_oper_payable': {'type': 'float', 'vaule': '经营性应收项目的减少', 'is_primary_key': 'no'},
                'incr_oper_payable': {'type': 'float', 'vaule': '经营性应付项目的增加', 'is_primary_key': 'no'},
                'others': {'type': 'float', 'vaule': '其他', 'is_primary_key': 'no'},
                'im_net_cashflow_oper_act': {'type': 'float', 'vaule': '经营活动产生的现金流量净额(间接法)', 'is_primary_key': 'no'},
                'conv_debt_into_cap': {'type': 'float', 'vaule': '债务转为资本', 'is_primary_key': 'no'},
                'conv_copbonds_due_within_1y': {'type': 'float', 'vaule': '一年内到期的可转换公司债券', 'is_primary_key': 'no'},
                'fa_fnc_leases': {'type': 'float', 'vaule': '融资租入固定资产', 'is_primary_key': 'no'},
                'end_bal_cash': {'type': 'float', 'vaule': '现金的期末余额', 'is_primary_key': 'no'},
                'beg_bal_cash': {'type': 'float', 'vaule': '减:现金的期初余额', 'is_primary_key': 'no'},
                'end_bal_cash_equ': {'type': 'float', 'vaule': '加:现金等价物的期末余额', 'is_primary_key': 'no'},
                'beg_bal_cash_equ': {'type': 'float', 'vaule': '减:现金等价物的期初余额', 'is_primary_key': 'no'},
                'im_n_incr_cash_equ': {'type': 'float', 'vaule': '现金及现金等价物净增加额(间接法)', 'is_primary_key': 'no'}}

    # 分红送股
    dividend = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                'end_date': {'type': 'str', 'vaule': '分红年度', 'is_primary_key': 'yes'},
                'ann_date': {'type': 'str', 'vaule': '预案公告日', 'is_primary_key': 'no'},
                'div_proc': {'type': 'str', 'vaule': '实施进度', 'is_primary_key': 'no'},
                'stk_div': {'type': 'float', 'vaule': '每股送转', 'is_primary_key': 'no'},
                'stk_bo_rate': {'type': 'float', 'vaule': '每股送股比例', 'is_primary_key': 'no'},
                'stk_co_rate': {'type': 'float', 'vaule': '每股转增比例', 'is_primary_key': 'no'},
                'cash_div': {'type': 'float', 'vaule': '每股分红（税后）', 'is_primary_key': 'no'},
                'cash_div_tax': {'type': 'float', 'vaule': '每股分红（税前）', 'is_primary_key': 'no'},
                'record_date': {'type': 'str', 'vaule': '股权登记日', 'is_primary_key': 'no'},
                'ex_date': {'type': 'str', 'vaule': '除权除息日', 'is_primary_key': 'no'},
                'pay_date': {'type': 'str', 'vaule': '派息日', 'is_primary_key': 'no'},
                'div_listdate': {'type': 'str', 'vaule': '红股上市日', 'is_primary_key': 'no'},
                'imp_ann_date': {'type': 'str', 'vaule': '实施公告日', 'is_primary_key': 'no'},
                'base_date': {'type': 'str', 'vaule': '基准日', 'is_primary_key': 'no'},
                'base_share': {'type': 'float', 'vaule': '基准股本（万）', 'is_primary_key': 'no'}}

    # 财务指标数据
    fina_indicator = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                      'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
                      'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
                      'eps': {'type': 'float', 'vaule': '基本每股收益', 'is_primary_key': 'no'},
                      'dt_eps': {'type': 'float', 'vaule': '稀释每股收益', 'is_primary_key': 'no'},
                      'total_revenue_ps': {'type': 'float', 'vaule': '每股营业总收入', 'is_primary_key': 'no'},
                      'revenue_ps': {'type': 'float', 'vaule': '每股营业收入', 'is_primary_key': 'no'},
                      'capital_rese_ps': {'type': 'float', 'vaule': '每股资本公积', 'is_primary_key': 'no'},
                      'surplus_rese_ps': {'type': 'float', 'vaule': '每股盈余公积', 'is_primary_key': 'no'},
                      'undist_profit_ps': {'type': 'float', 'vaule': '每股未分配利润', 'is_primary_key': 'no'},
                      'extra_item': {'type': 'float', 'vaule': '非经常性损益', 'is_primary_key': 'no'},
                      'profit_dedt': {'type': 'float', 'vaule': '扣除非经常性损益后的净利润', 'is_primary_key': 'no'},
                      'gross_margin': {'type': 'float', 'vaule': '毛利', 'is_primary_key': 'no'},
                      'current_ratio': {'type': 'float', 'vaule': '流动比率', 'is_primary_key': 'no'},
                      'quick_ratio': {'type': 'float', 'vaule': '速动比率', 'is_primary_key': 'no'},
                      'cash_ratio': {'type': 'float', 'vaule': '保守速动比率', 'is_primary_key': 'no'},
                      'invturn_days': {'type': 'float', 'vaule': '存货周转天数', 'is_primary_key': 'no'},
                      'arturn_days': {'type': 'float', 'vaule': '应收账款周转天数', 'is_primary_key': 'no'},
                      'inv_turn': {'type': 'float', 'vaule': '存货周转率', 'is_primary_key': 'no'},
                      'ar_turn': {'type': 'float', 'vaule': '应收账款周转率', 'is_primary_key': 'no'},
                      'ca_turn': {'type': 'float', 'vaule': '流动资产周转率', 'is_primary_key': 'no'},
                      'fa_turn': {'type': 'float', 'vaule': '固定资产周转率', 'is_primary_key': 'no'},
                      'assets_turn': {'type': 'float', 'vaule': '总资产周转率', 'is_primary_key': 'no'},
                      'op_income': {'type': 'float', 'vaule': '经营活动净收益', 'is_primary_key': 'no'},
                      'valuechange_income': {'type': 'float', 'vaule': '价值变动净收益', 'is_primary_key': 'no'},
                      'interst_income': {'type': 'float', 'vaule': '利息费用', 'is_primary_key': 'no'},
                      'daa': {'type': 'float', 'vaule': '折旧与摊销', 'is_primary_key': 'no'},
                      'ebit': {'type': 'float', 'vaule': '息税前利润', 'is_primary_key': 'no'},
                      'ebitda': {'type': 'float', 'vaule': '息税折旧摊销前利润', 'is_primary_key': 'no'},
                      'fcff': {'type': 'float', 'vaule': '企业自由现金流量', 'is_primary_key': 'no'},
                      'fcfe': {'type': 'float', 'vaule': '股权自由现金流量', 'is_primary_key': 'no'},
                      'current_exint': {'type': 'float', 'vaule': '无息流动负债', 'is_primary_key': 'no'},
                      'noncurrent_exint': {'type': 'float', 'vaule': '无息非流动负债', 'is_primary_key': 'no'},
                      'interestdebt': {'type': 'float', 'vaule': '带息债务', 'is_primary_key': 'no'},
                      'netdebt': {'type': 'float', 'vaule': '净债务', 'is_primary_key': 'no'},
                      'tangible_asset': {'type': 'float', 'vaule': '有形资产', 'is_primary_key': 'no'},
                      'working_capital': {'type': 'float', 'vaule': '营运资金', 'is_primary_key': 'no'},
                      'networking_capital': {'type': 'float', 'vaule': '营运流动资本', 'is_primary_key': 'no'},
                      'invest_capital': {'type': 'float', 'vaule': '全部投入资本', 'is_primary_key': 'no'},
                      'retained_earnings': {'type': 'float', 'vaule': '留存收益', 'is_primary_key': 'no'},
                      'diluted2_eps': {'type': 'float', 'vaule': '期末摊薄每股收益', 'is_primary_key': 'no'},
                      'bps': {'type': 'float', 'vaule': '每股净资产', 'is_primary_key': 'no'},
                      'ocfps': {'type': 'float', 'vaule': '每股经营活动产生的现金流量净额', 'is_primary_key': 'no'},
                      'retainedps': {'type': 'float', 'vaule': '每股留存收益', 'is_primary_key': 'no'},
                      'cfps': {'type': 'float', 'vaule': '每股现金流量净额', 'is_primary_key': 'no'},
                      'ebit_ps': {'type': 'float', 'vaule': '每股息税前利润', 'is_primary_key': 'no'},
                      'fcff_ps': {'type': 'float', 'vaule': '每股企业自由现金流量', 'is_primary_key': 'no'},
                      'fcfe_ps': {'type': 'float', 'vaule': '每股股东自由现金流量', 'is_primary_key': 'no'},
                      'netprofit_margin': {'type': 'float', 'vaule': '销售净利率', 'is_primary_key': 'no'},
                      'grossprofit_margin': {'type': 'float', 'vaule': '销售毛利率', 'is_primary_key': 'no'},
                      'cogs_of_sales': {'type': 'float', 'vaule': '销售成本率', 'is_primary_key': 'no'},
                      'expense_of_sales': {'type': 'float', 'vaule': '销售期间费用率', 'is_primary_key': 'no'},
                      'profit_to_gr': {'type': 'float', 'vaule': '净利润/营业总收入', 'is_primary_key': 'no'},
                      'saleexp_to_gr': {'type': 'float', 'vaule': '销售费用/营业总收入', 'is_primary_key': 'no'},
                      'adminexp_of_gr': {'type': 'float', 'vaule': '管理费用/营业总收入', 'is_primary_key': 'no'},
                      'finaexp_of_gr': {'type': 'float', 'vaule': '财务费用/营业总收入', 'is_primary_key': 'no'},
                      'impai_ttm': {'type': 'float', 'vaule': '资产减值损失/营业总收入', 'is_primary_key': 'no'},
                      'gc_of_gr': {'type': 'float', 'vaule': '营业总成本/营业总收入', 'is_primary_key': 'no'},
                      'op_of_gr': {'type': 'float', 'vaule': '营业利润/营业总收入', 'is_primary_key': 'no'},
                      'ebit_of_gr': {'type': 'float', 'vaule': '息税前利润/营业总收入', 'is_primary_key': 'no'},
                      'roe': {'type': 'float', 'vaule': '净资产收益率', 'is_primary_key': 'no'},
                      'roe_waa': {'type': 'float', 'vaule': '加权平均净资产收益率', 'is_primary_key': 'no'},
                      'roe_dt': {'type': 'float', 'vaule': '净资产收益率(扣除非经常损益)', 'is_primary_key': 'no'},
                      'roa': {'type': 'float', 'vaule': '总资产报酬率', 'is_primary_key': 'no'},
                      'npta': {'type': 'float', 'vaule': '总资产净利润', 'is_primary_key': 'no'},
                      'roic': {'type': 'float', 'vaule': '投入资本回报率', 'is_primary_key': 'no'},
                      'roe_yearly': {'type': 'float', 'vaule': '年化净资产收益率', 'is_primary_key': 'no'},
                      'roa2_yearly': {'type': 'float', 'vaule': '年化总资产报酬率', 'is_primary_key': 'no'},
                      'roe_avg': {'type': 'float', 'vaule': '平均净资产收益率(增发条件)', 'is_primary_key': 'no'},
                      'opincome_of_ebt': {'type': 'float', 'vaule': '经营活动净收益/利润总额', 'is_primary_key': 'no'},
                      'investincome_of_ebt': {'type': 'float', 'vaule': '价值变动净收益/利润总额', 'is_primary_key': 'no'},
                      'n_op_profit_of_ebt': {'type': 'float', 'vaule': '营业外收支净额/利润总额', 'is_primary_key': 'no'},
                      'tax_to_ebt': {'type': 'float', 'vaule': '所得税/利润总额', 'is_primary_key': 'no'},
                      'dtprofit_to_profit': {'type': 'float', 'vaule': '扣除非经常损益后的净利润/净利润', 'is_primary_key': 'no'},
                      'salescash_to_or': {'type': 'float', 'vaule': '销售商品提供劳务收到的现金/营业收入', 'is_primary_key': 'no'},
                      'ocf_to_or': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/营业收入', 'is_primary_key': 'no'},
                      'ocf_to_opincome': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/经营活动净收益', 'is_primary_key': 'no'},
                      'capitalized_to_da': {'type': 'float', 'vaule': '资本支出/折旧和摊销', 'is_primary_key': 'no'},
                      'debt_to_assets': {'type': 'float', 'vaule': '资产负债率', 'is_primary_key': 'no'},
                      'assets_to_eqt': {'type': 'float', 'vaule': '权益乘数', 'is_primary_key': 'no'},
                      'dp_assets_to_eqt': {'type': 'float', 'vaule': '权益乘数(杜邦分析)', 'is_primary_key': 'no'},
                      'ca_to_assets': {'type': 'float', 'vaule': '流动资产/总资产', 'is_primary_key': 'no'},
                      'nca_to_assets': {'type': 'float', 'vaule': '非流动资产/总资产', 'is_primary_key': 'no'},
                      'tbassets_to_totalassets': {'type': 'float', 'vaule': '有形资产/总资产', 'is_primary_key': 'no'},
                      'int_to_talcap': {'type': 'float', 'vaule': '带息债务/全部投入资本', 'is_primary_key': 'no'},
                      'eqt_to_talcapital': {'type': 'float', 'vaule': '归属于母公司的股东权益/全部投入资本', 'is_primary_key': 'no'},
                      'currentdebt_to_debt': {'type': 'float', 'vaule': '流动负债/负债合计', 'is_primary_key': 'no'},
                      'longdeb_to_debt': {'type': 'float', 'vaule': '非流动负债/负债合计', 'is_primary_key': 'no'},
                      'ocf_to_shortdebt': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/流动负债', 'is_primary_key': 'no'},
                      'debt_to_eqt': {'type': 'float', 'vaule': '产权比率', 'is_primary_key': 'no'},
                      'eqt_to_debt': {'type': 'float', 'vaule': '归属于母公司的股东权益/负债合计', 'is_primary_key': 'no'},
                      'eqt_to_interestdebt': {'type': 'float', 'vaule': '归属于母公司的股东权益/带息债务', 'is_primary_key': 'no'},
                      'tangibleasset_to_debt': {'type': 'float', 'vaule': '有形资产/负债合计', 'is_primary_key': 'no'},
                      'tangasset_to_intdebt': {'type': 'float', 'vaule': '有形资产/带息债务', 'is_primary_key': 'no'},
                      'tangibleasset_to_netdebt': {'type': 'float', 'vaule': '有形资产/净债务', 'is_primary_key': 'no'},
                      'ocf_to_debt': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/负债合计', 'is_primary_key': 'no'},
                      'ocf_to_interestdebt': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/带息债务', 'is_primary_key': 'no'},
                      'ocf_to_netdebt': {'type': 'float', 'vaule': '经营活动产生的现金流量净额/净债务', 'is_primary_key': 'no'},
                      'ebit_to_interest': {'type': 'float', 'vaule': '已获利息倍数(EBIT/利息费用)', 'is_primary_key': 'no'},
                      'longdebt_to_workingcapital': {'type': 'float', 'vaule': '长期债务与营运资金比率', 'is_primary_key': 'no'},
                      'ebitda_to_debt': {'type': 'float', 'vaule': '息税折旧摊销前利润/负债合计', 'is_primary_key': 'no'},
                      'turn_days': {'type': 'float', 'vaule': '营业周期', 'is_primary_key': 'no'},
                      'roa_yearly': {'type': 'float', 'vaule': '年化总资产净利率', 'is_primary_key': 'no'},
                      'roa_dp': {'type': 'float', 'vaule': '总资产净利率(杜邦分析)', 'is_primary_key': 'no'},
                      'fixed_assets': {'type': 'float', 'vaule': '固定资产合计', 'is_primary_key': 'no'},
                      'profit_prefin_exp': {'type': 'float', 'vaule': '扣除财务费用前营业利润', 'is_primary_key': 'no'},
                      'non_op_profit': {'type': 'float', 'vaule': '非营业利润', 'is_primary_key': 'no'},
                      'op_to_ebt': {'type': 'float', 'vaule': '营业利润／利润总额', 'is_primary_key': 'no'},
                      'nop_to_ebt': {'type': 'float', 'vaule': '非营业利润／利润总额', 'is_primary_key': 'no'},
                      'ocf_to_profit': {'type': 'float', 'vaule': '经营活动产生的现金流量净额／营业利润', 'is_primary_key': 'no'},
                      'cash_to_liqdebt': {'type': 'float', 'vaule': '货币资金／流动负债', 'is_primary_key': 'no'},
                      'cash_to_liqdebt_withinterest': {'type': 'float', 'vaule': '货币资金／带息流动负债', 'is_primary_key': 'no'},
                      'op_to_liqdebt': {'type': 'float', 'vaule': '营业利润／流动负债', 'is_primary_key': 'no'},
                      'op_to_debt': {'type': 'float', 'vaule': '营业利润／负债合计', 'is_primary_key': 'no'},
                      'roic_yearly': {'type': 'float', 'vaule': '年化投入资本回报率', 'is_primary_key': 'no'},
                      'profit_to_op': {'type': 'float', 'vaule': '利润总额／营业收入', 'is_primary_key': 'no'},
                      'q_opincome': {'type': 'float', 'vaule': '经营活动单季度净收益', 'is_primary_key': 'no'},
                      'q_investincome': {'type': 'float', 'vaule': '价值变动单季度净收益', 'is_primary_key': 'no'},
                      'q_dtprofit': {'type': 'float', 'vaule': '扣除非经常损益后的单季度净利润', 'is_primary_key': 'no'},
                      'q_eps': {'type': 'float', 'vaule': '每股收益(单季度)', 'is_primary_key': 'no'},
                      'q_netprofit_margin': {'type': 'float', 'vaule': '销售净利率(单季度)', 'is_primary_key': 'no'},
                      'q_gsprofit_margin': {'type': 'float', 'vaule': '销售毛利率(单季度)', 'is_primary_key': 'no'},
                      'q_exp_to_sales': {'type': 'float', 'vaule': '销售期间费用率(单季度)', 'is_primary_key': 'no'},
                      'q_profit_to_gr': {'type': 'float', 'vaule': '净利润／营业总收入(单季度)', 'is_primary_key': 'no'},
                      'q_saleexp_to_gr': {'type': 'float', 'vaule': '销售费用／营业总收入 (单季度)', 'is_primary_key': 'no'},
                      'q_adminexp_to_gr': {'type': 'float', 'vaule': '管理费用／营业总收入 (单季度)', 'is_primary_key': 'no'},
                      'q_finaexp_to_gr': {'type': 'float', 'vaule': '财务费用／营业总收入 (单季度)', 'is_primary_key': 'no'},
                      'q_impair_to_gr_ttm': {'type': 'float', 'vaule': '资产减值损失／营业总收入(单季度)', 'is_primary_key': 'no'},
                      'q_gc_to_gr': {'type': 'float', 'vaule': '营业总成本／营业总收入 (单季度)', 'is_primary_key': 'no'},
                      'q_op_to_gr': {'type': 'float', 'vaule': '营业利润／营业总收入(单季度)', 'is_primary_key': 'no'},
                      'q_roe': {'type': 'float', 'vaule': '净资产收益率(单季度)', 'is_primary_key': 'no'},
                      'q_dt_roe': {'type': 'float', 'vaule': '净资产单季度收益率(扣除非经常损益)', 'is_primary_key': 'no'},
                      'q_npta': {'type': 'float', 'vaule': '总资产净利润(单季度)', 'is_primary_key': 'no'},
                      'q_opincome_to_ebt': {'type': 'float', 'vaule': '经营活动净收益／利润总额(单季度)', 'is_primary_key': 'no'},
                      'q_investincome_to_ebt': {'type': 'float', 'vaule': '价值变动净收益／利润总额(单季度)', 'is_primary_key': 'no'},
                      'q_dtprofit_to_profit': {'type': 'float', 'vaule': '扣除非经常损益后的净利润／净利润(单季度)',
                                               'is_primary_key': 'no'},
                      'q_salescash_to_or': {'type': 'float', 'vaule': '销售商品提供劳务收到的现金／营业收入(单季度)',
                                            'is_primary_key': 'no'},
                      'q_ocf_to_sales': {'type': 'float', 'vaule': '经营活动产生的现金流量净额／营业收入(单季度)', 'is_primary_key': 'no'},
                      'q_ocf_to_or': {'type': 'float', 'vaule': '经营活动产生的现金流量净额／经营活动净收益(单季度)', 'is_primary_key': 'no'},
                      'basic_eps_yoy': {'type': 'float', 'vaule': '基本每股收益同比增长率(%)', 'is_primary_key': 'no'},
                      'dt_eps_yoy': {'type': 'float', 'vaule': '稀释每股收益同比增长率(%)', 'is_primary_key': 'no'},
                      'cfps_yoy': {'type': 'float', 'vaule': '每股经营活动产生的现金流量净额同比增长率(%)', 'is_primary_key': 'no'},
                      'op_yoy': {'type': 'float', 'vaule': '营业利润同比增长率(%)', 'is_primary_key': 'no'},
                      'ebt_yoy': {'type': 'float', 'vaule': '利润总额同比增长率(%)', 'is_primary_key': 'no'},
                      'netprofit_yoy': {'type': 'float', 'vaule': '归属母公司股东的净利润同比增长率(%)', 'is_primary_key': 'no'},
                      'dt_netprofit_yoy': {'type': 'float', 'vaule': '归属母公司股东的净利润-扣除非经常损益同比增长率(%)',
                                           'is_primary_key': 'no'},
                      'ocf_yoy': {'type': 'float', 'vaule': '经营活动产生的现金流量净额同比增长率(%)', 'is_primary_key': 'no'},
                      'roe_yoy': {'type': 'float', 'vaule': '净资产收益率(摊薄)同比增长率(%)', 'is_primary_key': 'no'},
                      'bps_yoy': {'type': 'float', 'vaule': '每股净资产相对年初增长率(%)', 'is_primary_key': 'no'},
                      'assets_yoy': {'type': 'float', 'vaule': '资产总计相对年初增长率(%)', 'is_primary_key': 'no'},
                      'eqt_yoy': {'type': 'float', 'vaule': '归属母公司的股东权益相对年初增长率(%)', 'is_primary_key': 'no'},
                      'tr_yoy': {'type': 'float', 'vaule': '营业总收入同比增长率(%)', 'is_primary_key': 'no'},
                      'or_yoy': {'type': 'float', 'vaule': '营业收入同比增长率(%)', 'is_primary_key': 'no'},
                      'q_gr_yoy': {'type': 'float', 'vaule': '营业总收入同比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_gr_qoq': {'type': 'float', 'vaule': '营业总收入环比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_sales_yoy': {'type': 'float', 'vaule': '营业收入同比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_sales_qoq': {'type': 'float', 'vaule': '营业收入环比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_op_yoy': {'type': 'float', 'vaule': '营业利润同比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_op_qoq': {'type': 'float', 'vaule': '营业利润环比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_profit_yoy': {'type': 'float', 'vaule': '净利润同比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_profit_qoq': {'type': 'float', 'vaule': '净利润环比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_netprofit_yoy': {'type': 'float', 'vaule': '归属母公司股东的净利润同比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'q_netprofit_qoq': {'type': 'float', 'vaule': '归属母公司股东的净利润环比增长率(%)(单季度)', 'is_primary_key': 'no'},
                      'equity_yoy': {'type': 'float', 'vaule': '净资产同比增长率', 'is_primary_key': 'no'},
                      'rd_exp': {'type': 'float', 'vaule': '研发费用', 'is_primary_key': 'no'}}

    # 财务审计意见
    fina_audit = {'ts_code': {'type': 'str', 'vaule': 'TS股票代码', 'is_primary_key': 'yes'},
                  'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
                  'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
                  'audit_result': {'type': 'str', 'vaule': '审计结果', 'is_primary_key': 'no'},
                  'audit_fees': {'type': 'float', 'vaule': '审计总费用（元）', 'is_primary_key': 'no'},
                  'audit_agency': {'type': 'str', 'vaule': '会计事务所', 'is_primary_key': 'no'},
                  'audit_sign': {'type': 'str', 'vaule': '签字会计师', 'is_primary_key': 'no'}}

    # 主营业务构成
    fina_mainbz = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                   'end_date': {'type': 'str', 'vaule': '报告期', 'is_primary_key': 'yes'},
                   'bz_item': {'type': 'str', 'vaule': '主营业务来源', 'is_primary_key': 'no'},
                   'bz_sales': {'type': 'float', 'vaule': '主营业务收入(元)', 'is_primary_key': 'no'},
                   'bz_profit': {'type': 'float', 'vaule': '主营业务利润(元)', 'is_primary_key': 'no'},
                   'bz_cost': {'type': 'float', 'vaule': '主营业务成本(元)', 'is_primary_key': 'no'},
                   'curr_type': {'type': 'str', 'vaule': '货币代码', 'is_primary_key': 'no'},
                   'update_flag': {'type': 'str', 'vaule': '是否更新', 'is_primary_key': 'no'}}

    # 其他
    double_field_name = ["open", "high", "low", "pre_close", "change1", "pct_chg", "vol", "amount", "basic_eps",
                         "diluted_eps", "total_revenue", "revenue", "int_income", "prem_earned", "comm_income",
                         "n_commis_income", "n_oth_income", "n_oth_b_income", "prem_income", "out_prem",
                         "une_prem_reser", "reins_income", "n_sec_tb_income", "n_sec_uw_income", "n_asset_mg_income",
                         "oth_b_income", "fv_value_chg_gain", "invest_income", "ass_invest_income", "forex_gain",
                         "total_cogs", "oper_cost", "int_exp", "comm_exp", "biz_tax_surchg", "sell_exp", "admin_exp",
                         "fin_exp", "assets_impair_loss", "prem_refund", "compens_payout", "reser_insur_liab",
                         "div_payt", "reins_exp", "oper_exp", "compens_payout_refu", "insur_reser_refu",
                         "reins_cost_refund", "other_bus_cost", "operate_profit", "non_oper_income", "non_oper_exp",
                         "nca_disploss", "total_profit", "income_tax", "n_income", "n_income_attr_p", "minority_gain",
                         "oth_compr_income", "t_compr_income", "compr_inc_attr_p", "compr_inc_attr_m_s", "ebit",
                         "ebitda", "insurance_exp", "undist_profit", "distable_profit", "total_share", "cap_rese",
                         "undistr_porfit", "surplus_rese", "special_rese", "money_cap", "trad_asset", "notes_receiv",
                         "accounts_receiv", "oth_receiv", "prepayment", "div_receiv", "int_receiv", "inventories",
                         "amor_exp", "nca_within_1y", "sett_rsrv", "loanto_oth_bank_fi", "premium_receiv",
                         "reinsur_receiv", "reinsur_res_receiv", "pur_resale_fa", "oth_cur_assets", "total_cur_assets",
                         "fa_avail_for_sale", "htm_invest", "lt_eqt_invest", "invest_real_estate", "time_deposits",
                         "oth_assets", "lt_rec", "fix_assets", "cip", "const_materials", "fixed_assets_disp",
                         "produc_bio_assets", "oil_and_gas_assets", "intan_assets", "r_and_d", "goodwill",
                         "lt_amor_exp", "defer_tax_assets", "decr_in_disbur", "oth_nca", "total_nca", "cash_reser_cb",
                         "depos_in_oth_bfi", "prec_metals", "deriv_assets", "rr_reins_une_prem", "rr_reins_outstd_cla",
                         "rr_reins_lins_liab", "rr_reins_lthins_liab", "refund_depos", "ph_pledge_loans",
                         "refund_cap_depos", "indep_acct_assets", "client_depos", "client_prov", "transac_seat_fee",
                         "invest_as_receiv", "total_assets", "lt_borr", "st_borr", "cb_borr", "depos_ib_deposits",
                         "loan_oth_bank", "trading_fl", "notes_payable", "acct_payable", "adv_receipts",
                         "sold_for_repur_fa", "comm_payable", "payroll_payable", "taxes_payable", "int_payable",
                         "div_payable", "oth_payable", "acc_exp", "deferred_inc", "st_bonds_payable",
                         "payable_to_reinsurer", "rsrv_insur_cont", "acting_trading_sec", "acting_uw_sec",
                         "non_cur_liab_due_1y", "oth_cur_liab", "total_cur_liab", "bond_payable", "lt_payable",
                         "specific_payables", "estimated_liab", "defer_tax_liab", "defer_inc_non_cur_liab", "oth_ncl",
                         "total_ncl", "depos_oth_bfi", "deriv_liab", "depos", "agency_bus_liab", "oth_liab",
                         "prem_receiv_adva", "depos_received", "ph_invest", "reser_une_prem", "reser_outstd_claims",
                         "reser_lins_liab", "reser_lthins_liab", "indept_acc_liab", "pledge_borr", "indem_payable",
                         "policy_div_payable", "total_liab", "treasury_share", "ordin_risk_reser", "forex_differ",
                         "invest_loss_unconf", "minority_int", "total_hldr_eqy_exc_min_int",
                         "total_hldr_eqy_inc_min_int", "total_liab_hldr_eqy", "lt_payroll_payable", "oth_comp_income",
                         "oth_eqt_tools", "oth_eqt_tools_p_shr", "lending_funds", "acc_receivable", "st_fin_payable",
                         "payables", "hfs_assets", "hfs_sales", "net_profit", "finan_exp",
                         "c_fr_sale_sg", "recp_tax_rends", "n_depos_incr_fi", "n_incr_loans_cb", "n_inc_borr_oth_fi",
                         "prem_fr_orig_contr", "n_incr_insured_dep", "n_reinsur_prem", "n_incr_disp_tfa",
                         "ifc_cash_incr", "n_incr_disp_faas", "n_incr_loans_oth_bank", "n_cap_incr_repur",
                         "c_fr_oth_operate_a",
                         "c_inf_fr_operate_a", "c_paid_goods_s", "c_paid_to_for_empl", "c_paid_for_taxes",
                         "n_incr_clt_loan_adv", "n_incr_dep_cbob", "c_pay_claims_orig_inco", "pay_handling_chrg",
                         "pay_comm_insur_plcy",
                         "oth_cash_pay_oper_act", "st_cash_out_act", "n_cashflow_act", "oth_recp_ral_inv_act",
                         "c_disp_withdrwl_invest", "c_recp_return_invest", "n_recp_disp_fiolta", "n_recp_disp_sobu",
                         "stot_inflows_inv_act", "c_pay_acq_const_fiolta", "c_paid_invest", "n_disp_subs_oth_biz",
                         "oth_pay_ral_inv_act", "n_incr_pledge_loan", "stot_out_inv_act", "n_cashflow_inv_act",
                         "c_recp_borrow", "proc_issue_bonds", "oth_cash_recp_ral_fnc_act", "stot_cash_in_fnc_act",
                         "free_cashflow",
                         "c_prepay_amt_borr", "c_pay_dist_dpcp_int_exp", "incl_dvd_profit_paid_sc_ms",
                         "oth_cashpay_ral_fnc_act", "stot_cashout_fnc_act", "n_cash_flows_fnc_act", "eff_fx_flu_cash",
                         "n_incr_cash_cash_equ",
                         "c_cash_equ_beg_period", "c_cash_equ_end_period", "c_recp_cap_contrib", "incl_cash_rec_saims",
                         "uncon_invest_loss", "prov_depr_assets", "depr_fa_coga_dpba", "amort_intang_assets",
                         "lt_amort_deferred_exp", "decr_deferred_exp", "incr_acc_exp", "loss_disp_fiolta",
                         "loss_scr_fa", "loss_fv_chg", "invest_loss", "decr_def_inc_tax_assets",
                         "incr_def_inc_tax_liab",
                         "decr_inventories", "decr_oper_payable", "incr_oper_payable", "others",
                         "im_net_cashflow_oper_act",
                         "conv_debt_into_cap", "conv_copbonds_due_within_1y", "fa_fnc_leases", "end_bal_cash",
                         "beg_bal_cash",
                         "end_bal_cash_equ", "beg_bal_cash_equ", "im_n_incr_cash_equ", "stk_div", "stk_bo_rate",
                         "stk_co_rate", "cash_div",
                         "cash_div_tax", "base_share", "eps", "dt_eps", "total_revenue_ps", "revenue_ps",
                         "capital_rese_ps", "surplus_rese_ps", "undist_profit_ps", "extra_item", "profit_dedt",
                         "gross_margin", "current_ratio", "quick_ratio", "cash_ratio", "invturn_days", "arturn_days",
                         "inv_turn", "ar_turn", "ca_turn", "fa_turn", "assets_turn", "op_income", "valuechange_income",
                         "interst_income", "daa", "ebit", "ebitda", "fcff", "fcfe", "current_exint", "noncurrent_exint",
                         "interestdebt", "netdebt", "tangible_asset", "working_capital", "networking_capital",
                         "invest_capital", "retained_earnings", "diluted2_eps", "bps", "ocfps", "retainedps", "cfps",
                         "ebit_ps", "fcff_ps", "fcfe_ps", "netprofit_margin", "grossprofit_margin", "cogs_of_sales",
                         "expense_of_sales", "profit_to_gr", "saleexp_to_gr", "adminexp_of_gr", "finaexp_of_gr",
                         "impai_ttm", "gc_of_gr", "op_of_gr", "ebit_of_gr", "roe", "roe_waa", "roe_dt", "roa", "npta",
                         "roic", "roe_yearly", "roa2_yearly", "roe_avg", "opincome_of_ebt", "investincome_of_ebt",
                         "n_op_profit_of_ebt", "tax_to_ebt", "dtprofit_to_profit", "salescash_to_or", "ocf_to_or",
                         "ocf_to_opincome", "capitalized_to_da", "debt_to_assets", "assets_to_eqt", "dp_assets_to_eqt",
                         "ca_to_assets", "nca_to_assets", "tbassets_to_totalassets", "int_to_talcap",
                         "eqt_to_talcapital", "currentdebt_to_debt", "longdeb_to_debt", "ocf_to_shortdebt",
                         "debt_to_eqt", "eqt_to_debt",
                         "eqt_to_interestdebt", "tangibleasset_to_debt", "tangasset_to_intdebt",
                         "tangibleasset_to_netdebt", "ocf_to_debt", "ocf_to_interestdebt", "ocf_to_netdebt",
                         "ebit_to_interest", "longdebt_to_workingcapital", "ebitda_to_debt", "turn_days", "roa_yearly",
                         "roa_dp", "fixed_assets", "profit_prefin_exp", "non_op_profit", "op_to_ebt", "nop_to_ebt",
                         "ocf_to_profit", "cash_to_liqdebt", "cash_to_liqdebt_withinterest", "op_to_liqdebt",
                         "op_to_debt", "roic_yearly", "profit_to_op", "q_opincome", "q_investincome", "q_dtprofit",
                         "q_eps",
                         "q_netprofit_margin", "q_gsprofit_margin", "q_exp_to_sales", "q_profit_to_gr",
                         "q_saleexp_to_gr", "q_adminexp_to_gr", "q_finaexp_to_gr", "q_impair_to_gr_ttm", "q_gc_to_gr",
                         "q_op_to_gr",
                         "q_roe", "q_dt_roe", "q_npta", "q_opincome_to_ebt", "q_investincome_to_ebt",
                         "q_dtprofit_to_profit",
                         "q_salescash_to_or", "q_ocf_to_sales", "q_ocf_to_or", "basic_eps_yoy", "dt_eps_yoy",
                         "cfps_yoy", "op_yoy", "ebt_yoy", "netprofit_yoy", "dt_netprofit_yoy", "ocf_yoy", "roe_yoy",
                         "bps_yoy",
                         "assets_yoy", "eqt_yoy", "tr_yoy", "or_yoy", "q_gr_yoy", "q_gr_qoq", "q_sales_yoy",
                         "q_sales_qoq", "q_op_yoy", "q_op_qoq", "q_profit_yoy", "q_profit_qoq", "q_netprofit_yoy",
                         "q_netprofit_qoq",
                         "equity_yoy", "rd_exp", "audit_fees", "bz_sales", "bz_profit", "bz_cost"]

    # -------------------------------------------------------------指数------------------------------------------------------------
    # 指数基本信息
    index_basic = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                   'name': {'type': 'str', 'vaule': '简称', 'is_primary_key': 'no'},
                   'fullname': {'type': 'str', 'vaule': '指数全称', 'is_primary_key': 'no'},
                   'market': {'type': 'str', 'vaule': '市场', 'is_primary_key': 'no'},
                   'publisher': {'type': 'str', 'vaule': '发布方', 'is_primary_key': 'no'},
                   'index_type': {'type': 'str', 'vaule': '指数风格', 'is_primary_key': 'no'},
                   'category': {'type': 'str', 'vaule': '指数类别', 'is_primary_key': 'no'},
                   'base_date': {'type': 'str', 'vaule': '基期', 'is_primary_key': 'no'},
                   'base_point': {'type': 'float', 'vaule': '基点', 'is_primary_key': 'no'},
                   'list_date': {'type': 'str', 'vaule': '发布日期', 'is_primary_key': 'no'},
                   'weight_rule': {'type': 'str', 'vaule': '加权方式', 'is_primary_key': 'no'},
                   'desc': {'type': 'str', 'vaule': '描述', 'is_primary_key': 'no'},
                   'exp_date': {'type': 'str', 'vaule': '终止日期', 'is_primary_key': 'no'}}

    # 指数日线行情
    index_daily = {'ts_code': {'type': 'str', 'vaule': 'TS指数代码', 'is_primary_key': 'yes'},
                   'trade_date': {'type': 'str', 'vaule': '交易日', 'is_primary_key': 'yes'},
                   'close': {'type': 'float', 'vaule': '收盘点位', 'is_primary_key': 'no'},
                   'open': {'type': 'float', 'vaule': '开盘点位', 'is_primary_key': 'no'},
                   'high': {'type': 'float', 'vaule': '最高点位', 'is_primary_key': 'no'},
                   'low': {'type': 'float', 'vaule': '最低点位', 'is_primary_key': 'no'},
                   'pre_close': {'type': 'float', 'vaule': '昨日收盘点', 'is_primary_key': 'no'},
                   'change': {'type': 'float', 'vaule': '涨跌点', 'is_primary_key': 'no'},
                   'pct_chg': {'type': 'float', 'vaule': '涨跌幅', 'is_primary_key': 'no'},
                   'vol': {'type': 'float', 'vaule': '成交量（手）', 'is_primary_key': 'no'},
                   'amount': {'type': 'float', 'vaule': '成交额（千元）', 'is_primary_key': 'no'}}

    # 指数成分表和权重
    index_weight = {'index_code': {'type': 'str', 'vaule': '指数代码', 'is_primary_key': 'yes'},
                    'con_code': {'type': 'str', 'vaule': '成分代码', 'is_primary_key': 'yes'},
                    'trade_date': {'type': 'str', 'vaule': '交易日期', 'is_primary_key': 'yes'},
                    'weight': {'type': 'float', 'vaule': '权重', 'is_primary_key': 'no'}}

    # 大盘指数每日指标
    index_dailybasic = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                        'trade_date': {'type': 'str', 'vaule': '交易日期', 'is_primary_key': 'yes'},
                        'total_mv': {'type': 'float', 'vaule': '当日总市值（元）', 'is_primary_key': 'no'},
                        'float_mv': {'type': 'float', 'vaule': '当日流通市值（元）', 'is_primary_key': 'no'},
                        'total_share': {'type': 'float', 'vaule': '当日总股本（股）', 'is_primary_key': 'no'},
                        'float_share': {'type': 'float', 'vaule': '当日流通股本（股）', 'is_primary_key': 'no'},
                        'free_share': {'type': 'float', 'vaule': '当日自由流通股本（股）', 'is_primary_key': 'no'},
                        'turnover_rate': {'type': 'float', 'vaule': '换手率', 'is_primary_key': 'no'},
                        'turnover_rate_f': {'type': 'float', 'vaule': '换手率(基于自由流通股本)', 'is_primary_key': 'no'},
                        'pe': {'type': 'float', 'vaule': '市盈率', 'is_primary_key': 'no'},
                        'pe_ttm': {'type': 'float', 'vaule': '市盈率TTM', 'is_primary_key': 'no'},
                        'pb': {'type': 'float', 'vaule': '市净率', 'is_primary_key': 'no'}}


    # -------------------------------------------------------------公募基金------------------------------------------------------------
    # 公募基金列表
    fund_basic = {'ts_code': {'type': 'str', 'vaule': '基金代码', 'is_primary_key': 'yes'},
                  'name': {'type': 'str', 'vaule': '简称', 'is_primary_key': 'no'},
                  'management': {'type': 'str', 'vaule': '管理人', 'is_primary_key': 'no'},
                  'custodian': {'type': 'str', 'vaule': '托管人', 'is_primary_key': 'no'},
                  'fund_type': {'type': 'str', 'vaule': '投资类型', 'is_primary_key': 'no'},
                  'found_date': {'type': 'str', 'vaule': '成立日期', 'is_primary_key': 'no'},
                  'due_date': {'type': 'str', 'vaule': '到期日期', 'is_primary_key': 'no'},
                  'list_date': {'type': 'str', 'vaule': '上市时间', 'is_primary_key': 'no'},
                  'issue_date': {'type': 'str', 'vaule': '发行日期', 'is_primary_key': 'no'},
                  'delist_date': {'type': 'str', 'vaule': '退市日期', 'is_primary_key': 'no'},
                  'issue_amount': {'type': 'float', 'vaule': '发行份额(亿)', 'is_primary_key': 'no'},
                  'm_fee': {'type': 'float', 'vaule': '管理费', 'is_primary_key': 'no'},
                  'c_fee': {'type': 'float', 'vaule': '托管费', 'is_primary_key': 'no'},
                  'duration_year': {'type': 'float', 'vaule': '存续期', 'is_primary_key': 'no'},
                  'p_value': {'type': 'float', 'vaule': '面值', 'is_primary_key': 'no'},
                  'min_amount': {'type': 'float', 'vaule': '起点金额(万元)', 'is_primary_key': 'no'},
                  'exp_return': {'type': 'float', 'vaule': '预期收益率', 'is_primary_key': 'no'},
                  'benchmark': {'type': 'str', 'vaule': '业绩比较基准', 'is_primary_key': 'no'},
                  'status': {'type': 'str', 'vaule': '存续状态D摘牌 I发行 L已上市', 'is_primary_key': 'no'},
                  'invest_type': {'type': 'str', 'vaule': '投资风格', 'is_primary_key': 'no'},
                  'type': {'type': 'str', 'vaule': '基金类型', 'is_primary_key': 'no'},
                  'trustee': {'type': 'str', 'vaule': '受托人', 'is_primary_key': 'no'},
                  'purc_startdate': {'type': 'str', 'vaule': '日常申购起始日', 'is_primary_key': 'no'},
                  'redm_startdate': {'type': 'str', 'vaule': '日常赎回起始日', 'is_primary_key': 'no'},
                  'market': {'type': 'str', 'vaule': 'E场内O场外', 'is_primary_key': 'no'}}
    # 公募基金管理人列表
    fund_company = {'name': {'type': 'str', 'vaule': '基金公司名称', 'is_primary_key': 'yes'},
                    'shortname': {'type': 'str', 'vaule': '简称', 'is_primary_key': 'no'},
                    'short_enname': {'type': 'str', 'vaule': '英文缩写', 'is_primary_key': 'no'},
                    'province': {'type': 'str', 'vaule': '省份', 'is_primary_key': 'no'},
                    'city': {'type': 'str', 'vaule': '城市', 'is_primary_key': 'no'},
                    'address': {'type': 'str', 'vaule': '注册地址', 'is_primary_key': 'no'},
                    'phone': {'type': 'str', 'vaule': '电话', 'is_primary_key': 'no'},
                    'office': {'type': 'str', 'vaule': '办公地址', 'is_primary_key': 'no'},
                    'website': {'type': 'str', 'vaule': '公司网址', 'is_primary_key': 'no'},
                    'chairman': {'type': 'str', 'vaule': '法人代表', 'is_primary_key': 'no'},
                    'manager': {'type': 'str', 'vaule': '总经理', 'is_primary_key': 'no'},
                    'reg_capital': {'type': 'float', 'vaule': '注册资本', 'is_primary_key': 'no'},
                    'setup_date': {'type': 'str', 'vaule': '成立日期', 'is_primary_key': 'no'},
                    'end_date': {'type': 'str', 'vaule': '公司终止日期', 'is_primary_key': 'no'},
                    'employees': {'type': 'float', 'vaule': '员工总数', 'is_primary_key': 'no'},
                    'main_business': {'type': 'str', 'vaule': '主要产品及业务', 'is_primary_key': 'no'},
                    'org_code': {'type': 'str', 'vaule': '组织机构代码', 'is_primary_key': 'no'},
                    'credit_code': {'type': 'str', 'vaule': '统一社会信用代码', 'is_primary_key': 'no'}}
    # 公募基金净值
    fund_nav = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'no'},
                'end_date': {'type': 'str', 'vaule': '截止日期', 'is_primary_key': 'yes'},
                'unit_nav': {'type': 'float', 'vaule': '单位净值', 'is_primary_key': 'no'},
                'accum_nav': {'type': 'float', 'vaule': '累计净值', 'is_primary_key': 'no'},
                'accum_div': {'type': 'float', 'vaule': '累计分红', 'is_primary_key': 'no'},
                'net_asset': {'type': 'float', 'vaule': '资产净值', 'is_primary_key': 'no'},
                'total_netasset': {'type': 'float', 'vaule': '合计资产净值', 'is_primary_key': 'no'},
                'adj_nav': {'type': 'float', 'vaule': '复权单位净值', 'is_primary_key': 'no'}}
    # 公墓基金分红数据
    fund_div = {'ts_code': {'type': 'str', 'vaule': 'TS代码', 'is_primary_key': 'yes'},
                'ann_date': {'type': 'str', 'vaule': '公告日期', 'is_primary_key': 'yes'},
                'imp_anndate': {'type': 'str', 'vaule': '分红实施公告日', 'is_primary_key': 'no'},
                'base_date': {'type': 'str', 'vaule': '分配收益基准日', 'is_primary_key': 'no'},
                'div_proc': {'type': 'str', 'vaule': '方案进度', 'is_primary_key': 'no'},
                'record_date': {'type': 'str', 'vaule': '权益登记日', 'is_primary_key': 'no'},
                'ex_date': {'type': 'str', 'vaule': '除息日', 'is_primary_key': 'no'},
                'pay_date': {'type': 'str', 'vaule': '派息日', 'is_primary_key': 'no'},
                'earpay_date': {'type': 'str', 'vaule': '收益支付日', 'is_primary_key': 'no'},
                'net_ex_date': {'type': 'str', 'vaule': '净值除权日', 'is_primary_key': 'no'},
                'div_cash': {'type': 'float', 'vaule': '每股派息(元)', 'is_primary_key': 'no'},
                'base_unit': {'type': 'float', 'vaule': '基准基金份额(万份)', 'is_primary_key': 'no'},
                'ear_distr': {'type': 'float', 'vaule': '可分配收益(元)', 'is_primary_key': 'no'},
                'ear_amount': {'type': 'float', 'vaule': '收益分配金额(元)', 'is_primary_key': 'no'},
                'account_date': {'type': 'str', 'vaule': '红利再投资到账日', 'is_primary_key': 'no'},
                'base_year': {'type': 'str', 'vaule': '份额基准年度', 'is_primary_key': 'no'}}

    # -------------------------------------------------------------利率数据------------------------------------------------------------
    # shibor
    shibor = {'date': {'type': 'str', 'vaule': '日期', 'is_primary_key': 'yes'},
              'on': {'type': 'float', 'vaule': '隔夜', 'is_primary_key': 'no'},
              '1w': {'type': 'float', 'vaule': '1周', 'is_primary_key': 'no'},
              '2w': {'type': 'float', 'vaule': '2周', 'is_primary_key': 'no'},
              '1m': {'type': 'float', 'vaule': '1个月', 'is_primary_key': 'no'},
              '3m': {'type': 'float', 'vaule': '3个月', 'is_primary_key': 'no'},
              '6m': {'type': 'float', 'vaule': '6个月', 'is_primary_key': 'no'},
              '9m': {'type': 'float', 'vaule': '9个月', 'is_primary_key': 'no'},
              '1y': {'type': 'float', 'vaule': '1年', 'is_primary_key': 'no'}}
    # LPR报价
    shibor_lpr = {'date': {'type': 'str', 'vaule': '日期', 'is_primary_key': 'yes'},
                  '1y': {'type': 'float', 'vaule': '1年贷款利率', 'is_primary_key': 'no'}}
    # libor
    libor = {'date': {'type': 'str', 'vaule': '日期', 'is_primary_key': 'yes'},
             'curr_type': {'type': 'str', 'vaule': '货币', 'is_primary_key': 'no'},
             'on': {'type': 'float', 'vaule': '隔夜', 'is_primary_key': 'no'},
             '1w': {'type': 'float', 'vaule': '1周', 'is_primary_key': 'no'},
             '1m': {'type': 'float', 'vaule': '1个月', 'is_primary_key': 'no'},
             '2m': {'type': 'float', 'vaule': '2个月', 'is_primary_key': 'no'},
             '3m': {'type': 'float', 'vaule': '3个月', 'is_primary_key': 'no'},
             '6m': {'type': 'float', 'vaule': '6个月', 'is_primary_key': 'no'},
             '12m': {'type': 'float', 'vaule': '12个月', 'is_primary_key': 'no'}}
    # hibor
    hibor = {'date': {'type': 'str', 'vaule': '日期', 'is_primary_key': 'yes'},
             'on': {'type': 'float', 'vaule': '隔夜', 'is_primary_key': 'no'},
             '1w': {'type': 'float', 'vaule': '1周', 'is_primary_key': 'no'},
             '2w': {'type': 'float', 'vaule': '2周', 'is_primary_key': 'no'},
             '1m': {'type': 'float', 'vaule': '1个月', 'is_primary_key': 'no'},
             '2m': {'type': 'float', 'vaule': '2个月', 'is_primary_key': 'no'},
             '3m': {'type': 'float', 'vaule': '3个月', 'is_primary_key': 'no'},
             '6m': {'type': 'float', 'vaule': '6个月', 'is_primary_key': 'no'},
             '12m': {'type': 'float', 'vaule': '12个月', 'is_primary_key': 'no'}}


    # ------------------------------------------------------------其他数据------------------------------------------------------------
    sql_key_word = ["change", "desc", "on"]
    time_ranges = [["19900101","19950101"],["19950101","20000101"],["20010101","20050101"],["20050101","20100101"],["20100101","20150101"],["20150101","20200101"]]